name: Publish Package to NPM

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      NPM_ACCESS_TOKEN:
        required: true

jobs:
  publish-npm:
    if: github.event_name == 'release' && github.event.action == 'created'
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"
          registry-url: https://registry.npmjs.org
          # Defaults to the user or organization that owns the workflow file
          scope: "@codrjs"
      - run: yarn
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
      - run: cd dist && yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
