name: Publish Package to NPM

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      NPM_ACCESS_TOKEN:
        required: true

jobs:
  publish-npm:
    if: github.event_name == 'release' && github.event.action == 'created'
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
          registry-url: https://registry.npmjs.org
          # Defaults to the user or organization that owns the workflow file
          scope: "@codrjs"
      - name: Install Dependancies
        run: yarn
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Publish Artifact
        run: cd dist && yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
