name: Test NodeJS Artifact

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
      - run: yarn
      - run: yarn test
