name: Test NodeJS Code

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      MONGO_URI:
        required: true
      JWT_SECRET:
        required: true
    inputs:
      JWT_ALGORITHM:
        required: true
        type: string
      JWT_ISSUER:
        required: true
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"
          cache: "yarn"
      - name: Install Dependancies
        run: yarn
      - name: Build Code
        run: yarn build
      - name: Run Tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_ALGORITHM: ${{ inputs.JWT_ALGORITHM }}
          JWT_ISSUER: ${{ inputs.JWT_ISSUER }}
        run: yarn test
